#!/bin/sh

version="$(script/version)"
echo $version

rsync ishtar:~/comrak/comrak-$version-x86_64-unknown-linux-gnu .
rsync debian:~/comrak/comrak-$version-aarch64-unknown-linux-gnu .
rsync talia:~/Code/comrak/comrak-$version-x86_64-unknown-freebsd .
rsync /Volumes/comrak/comrak-$version-x86_64-pc-windows-msvc.exe .
