#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

version="$(script/version)"

function build {
    local rust_ver="$1"
    local flake_ref="$2"

    echo "--- building $flake_ref"
    nix build ".#$flake_ref" &&
        cp result/bin/comrak "comrak-$version-$rust_ver"
}

build aarch64-apple-darwin packages.aarch64-darwin.default
build x86_64-apple-darwin packages.x86_64-darwin.default
build aarch64-unknown-linux-gnu packages.aarch64-linux.default
build x86_64-unknown-linux-gnu packages.x86_64-linux.default

file "comrak-$version-"*
