#!/bin/sh
version="$(script/version)"
echo $version

cargo +stable build --release
mv target/release/comrak comrak-$version-aarch64-apple-darwin

rustup +stable target add x86_64-apple-darwin
cargo +stable build --release --target=x86_64-apple-darwin
mv target/x86_64-apple-darwin/release/comrak comrak-$version-x86_64-apple-darwin

rustup +stable target add armv7-unknown-linux-musleabihf
brew tap messense/macos-cross-toolchains
brew install armv7-unknown-linux-musleabihf
ln -sf $(which armv7-unknown-linux-musleabihf-gcc) ~/.local/bin/arm-linux-musleabihf-gcc
cargo +stable build --release --target=armv7-unknown-linux-musleabihf
mv target/armv7-unknown-linux-musleabihf/release/comrak comrak-$version-armv7-unknown-linux-musleabihf
