#!/usr/bin/env ruby

require 'commonmarker'

HELP = "$ comrak --help\n"

readme = File.read File.join(File.dirname(__FILE__), '../README.md')

doc = CommonMarker.render_doc(readme)
doc.walk do |node|
  if node.type == :code_block && node.string_content.start_with?(HELP)
    node.string_content = "#{HELP}#{`cargo run -- --help`}"
  end
end

File.open(File.join(File.dirname(__FILE__), '../README.md'), 'w') do |f|
  f.write doc.to_commonmark
end
